

{ config, pkgs, lib, ... }:

with lib;
let
  cfg = config.modules.eww;
  c = config.lib.stylix.colors;
in {
  options.modules.eww = { enable = mkEnableOption "eww"; };
  config = mkIf cfg.enable {
    home.packages = with pkgs; [
      eww upower socat
      jaq ripgrep bluez
      bc networkmanager pulseaudio
      wireplumber material-symbols
    ];

    home.file.".config/eww/eww.scss".source = ./eww.scss;
    home.file.".config/eww/eww.yuck".source = ./eww.yuck;
    home.file.".config/eww/pollers.yuck".source = ./pollers.yuck;
    home.file.".config/eww/launch".source = ./launch;

    home.file.".config/eww/assets".source = ./assets;
    home.file.".config/eww/modules".source = ./modules;
    home.file.".config/eww/scripts".source = ./scripts;
    home.file.".config/eww/windows".source = ./windows;

    # CSS files — individually sourced so _colors.scss can be generated from base16
    home.file.".config/eww/css/_calendar.scss".source = ./css/_calendar.scss;
    home.file.".config/eww/css/_music.scss".source    = ./css/_music.scss;
    home.file.".config/eww/css/_osd.scss".source      = ./css/_osd.scss;
    home.file.".config/eww/css/_sidebar.scss".source  = ./css/_sidebar.scss;
    home.file.".config/eww/css/_system.scss".source   = ./css/_system.scss;
    home.file.".config/eww/css/_volume.scss".source   = ./css/_volume.scss;

    # Generated from stylix base16 — keeps all old catppuccin variable names as aliases
    home.file.".config/eww/css/_colors.scss".text = ''
      $fg:        #${c.base05};
      $bg:        #${c.base00};
      $bg1:       #${c.base01};
      $border:    #${c.base02};
      $shadow:    #${c.base00};

      $text:      #${c.base05};
      $subtext1:  #${c.base04};
      $subtext0:  #${c.base03};
      $overlay2:  #${c.base03};
      $overlay1:  #${c.base03};
      $overlay0:  #${c.base03};

      $surface2:  #${c.base02};
      $surface1:  #${c.base01};
      $surface0:  #${c.base01};

      $base:      #${c.base00};
      $mantle:    #${c.base00};
      $crust:     #${c.base00};

      $rosewater: #${c.base06};
      $flamingo:  #${c.base08};
      $pink:      #${c.base0E};
      $mauve:     #${c.base0E};
      $red:       #${c.base08};
      $maroon:    #${c.base08};
      $peach:     #${c.base09};
      $yellow:    #${c.base0A};
      $green:     #${c.base0B};
      $teal:      #${c.base0C};
      $sky:       #${c.base0C};
      $sapphire:  #${c.base0C};
      $blue:      #${c.base0D};
      $lavender:  #${c.base0D};
      $white:     #${c.base07};
    '';

    # Shared color definitions sourced by scripts — generated from base16
    home.file.".config/eww/colors".text = ''
      #!/usr/bin/env bash
      # Generated by home-manager — do not edit, changes will be overwritten
      # Workspace indicator colors (one per monitor index: 0–3)
      colors=("#${c.base08}" "#${c.base09}" "#${c.base0B}" "#${c.base0D}")
      dimmed=("#${c.base08}88" "#${c.base09}88" "#${c.base0B}88" "#${c.base0D}88")
      empty="#${c.base01}"
      # Network
      color_net_connected="#${c.base0E}"
      color_net_disconnected="#${c.base03}"
      # Bluetooth
      color_bt_connected="#${c.base0D}"
      color_bt_off="#${c.base02}"
    '';

  # systemd.user.services.eww = {
  #   Unit = {
  #     Description = "Eww bar";
  #     After = [ "graphical-session.target" ];
  #   };
  #   Service = {
  #     ExecStart = "${eww}/launch";
  #     Restart = "always";
  #     RestartSec = 5;
  #   };
  #   Install = {
  #     WantedBy = [ "default.target" ];
  #   };
  # };

    home.sessionVariables = {
      EWW_CONFIG_DIR = "${config.home.homeDirectory}/.config/eww";
    };

   #systemd.user.services.eww.enable = true;
  };
}
