
#
# \ \        / (_)         | |                   |  __ \     | |
#  \ \  /\  / / _ _ __   __| | _____      _____  | |__) |   _| | ___  ___
#   \ \/  \/ / | | '_ \ / _` |/ _ \ \ /\ / / __| |  _  / | | | |/ _ \/ __|
#    \  /\  /  | | | | | (_| | (_) \ V  V /\__ \ | | \ \ |_| | |  __/\__ \
#     \/  \/   |_|_| |_|\__,_|\___/ \_/\_/ |___/ |_|  \_\__,_|_|\___||___/
#


# Float Necessary Windows
windowrule = match:class ^(Rofi)$, float on
windowrule = match:class ^(pavucontrol)$, float on
windowrule = match:class ^()$ match:title ^(Picture in picture)$, float on
windowrule = match:class ^(brave)$ match:title ^(Save File)$, float on
windowrule = match:class ^(brave)$ match:title ^(Open File)$, float on
windowrule = match:class ^(blueman-manager)$, float on
windowrule = match:class ^(org.twosheds.iwgtk)$, float on
windowrule = match:class ^(blueberry.py)$, float on
windowrule = match:class ^(xdg-desktop-portal-gtk)$, float on
windowrule = match:class ^(geeqie)$, float on
windowrule = match:class ^(eduvpn-gui)$, float on
windowrule = match:class ^(pomodoro)$, float on
windowrule = match:class ^(com.yubico.yubioath)$, float on
# Increase the opacity
windowrule = match:class discord, opacity 0.96
#windowrule = match:class VSCodium, opacity 0.9

## No gaps when only
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule = match:float false match:workspace w[tv1], border_size 0
windowrule = match:float false match:workspace w[tv1], rounding 0
windowrule = match:float false match:workspace f[1], border_size 0
windowrule = match:float false match:workspace f[1], rounding 0

#^.*nvim.*$
#windowrule=opacity 1,neovim

# Noctalia settings window
windowrule = match:class ^(dev\.noctalia\.Noctalia)$, float on
windowrule = match:class ^(dev\.noctalia\.Noctalia)$, size 1080 920


